### navigation settings ########################################################

# whether NAO should execute its footsteps slow but accurate or fast and
# inaccurate
safe_execution: False 

# feedback rate of the action server
feedback_frequency: 5.0

accuracy:
  # the smaller the better a performed footstep has to fit into a planned one
  footstep: {x: 0.02, y: 0.02, theta: 0.1}
